#!/bin/bash

rm -rf temp/
mkdir temp/ && cd temp

CMAKE_BUILD_TYPE=Release
CMAKE_TOOLCHAIN_FILE=/home/andreas/Code/Android/SDK/ndk/21.3.6528147/build/cmake/android.toolchain.cmake
CMAKE_INSTALL_PREFIX=""

ANDROID_ABI=armeabi-v7a
ANDROID_TOOLCHAIN=clang
ANDROID_ARM_NEON=ON
ANDROID_NATIVE_API_LEVEL=24

DESTDIR=../build

cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE -DANDROID_ABI=$ABI -DANDROID_TOOLCHAIN=$ANDROID_TOOLCHAIN -DANDROID_ARM_NEON=$ANDROID_ARM_NEON -DANDROID_NATIVE_API_LEVEL=$ANDROID_NATIVE_API_LEVEL -DCMAKE_INSTALL_PREFIX=$CMAKE_INSTALL_PREFIX ../

make -j4 install DESTDIR=$DESTDIR
